### ISSUE TITLE
Marine data publishing workshop 21 and 22 September 2023

### ISSUE THREAD

**Issue by lhmarsden** [gbif-norway/helpdesk#143] opened 2023-04-11 07:31 UTC
In September 2022, we ran a successful workshop together: 
https://github.com/gbif-norway/helpdesk/issues/73
https://www.gbif.no/events/2022/nansen-legacy-tromso.html

Researchers from the Nansen Legacy project came and worked on preparing their data for publication. I have since had many requests for this workshop to be repeated.

We likely have many Nansen Legacy researchers who would like to attend. However, perhaps other researchers outside of the project would also like to attend? How should we fund this? I think it is likely that Nansen Legacy would fund researchers from the project to attend, and could contribute to other costs - though this is not for me to decide.

@dagendresen suggested that we could host the event at Tøyen or at another campus at UiO in Oslo which would be suitable for me.

**Comment by dagendresen** [comment] 2023-04-11 07:52
GBIF Norway can certainly cover costs for the venue and lunch for participants. Would be good if participants are able to cover their own travel and hotel costs?

**Comment by lhmarsden** [comment] 2023-04-11 09:41
I think that sounds like a great approach!

We are probably too late to do it before the summer, but when are you all available after?

**Comment by dagendresen** [comment] 2023-04-11 16:47
For me August and September (except week 36, 4-8/9) are possible. October is rather busy, in November week 45 (6-10/10) is tentatively busy. December is possible.

**Comment by aaltenburger2** [comment] 2023-04-12 09:54
I think September is a good choice. I will be in Oslo 19.09. - 20.09. for a different workshop. 21.09.-22.09. would work well for me. I can contribute to the planning from Tromsø.

**Comment by rukayaj** [comment] 2023-04-12 12:20
21.09.-22.09 is ok for me too

**Comment by lhmarsden** [comment] 2023-04-14 09:10
21.09.-22.09 is ok for me too

**Comment by rukayaj** [comment] 2023-04-14 11:08
Did you have a venue in mind, Luke?

**Comment by lhmarsden** [comment] 2023-04-14 11:14
@dagendresen suggested Tøyen or at another campus at UiO in Oslo. Either is fine for me. You know better than me about what is suitable in Oslo!

**Comment by rukayaj** [comment] 2023-04-14 11:15
If you want I can book the manor house in Tøyen for you. If i can work out how to do that :)

**Comment by lhmarsden** [comment] 2023-04-14 11:17
That's great. 

So the plan is for GBIF to cover the venue and lunches/snacks, and researchers will use their own money to travel, right?

Will the workshop be free?

Nansen Legacy will almost certainly fund their own researchers to attend, but I think this can be open to anyone - not just Nansen Legacy researchers

**Comment by dagendresen** [comment] 2023-04-14 12:06
Agree good to focus on Nansen Legacy researchers, but keep the workshop open and free of cost for anybody who wants to attend (we can certainly cover lunch and coffee for all from the GBIF-node - just need some kind of registration to know how many wants lunch).

**Comment by lhmarsden** [comment] 2023-04-17 06:59
I can probably create some kind of registration in the same way as before. I need confirmation from the Nansen Legacy board that they are willing to fund researchers to attend. I guess I will get it this week or next.

**Comment by lhmarsden** [comment] 2023-04-21 06:37
We have the green light from Nansen Legacy that they will fund their researchers to attend this workshop on 21.09 - 22.09. 

Is the venue booked? I can create an event in eventbrite like last time if that works for people?

**Comment by dagendresen** [comment] 2023-04-24 10:54
We book Tøyen Manor here
https://www.uio.no/om/regelverk/eiendom/leie-lokaler/toyen-hovedgard/index.html
https://www.uio.no/om/finn-fram/omrader/toyen/to01/

**Comment by rukayaj** [comment] 2023-04-24 12:23
Thanks Dag! I have filled in the form for booking.

**Comment by lhmarsden** [comment] 2023-04-26 13:21
I have started drafting out the event on Eventbrite: https://www.eventbrite.com/e/bring-and-publish-your-data-workshop-darwin-core-archive-tickets-625228012817

I need some more details.

- Is the venue now booked?
- Can you confirm this is the venue? https://www.visitoslo.com/en/product/?tlp=2982773
- What is the capacity of the venue? How many people can attend?
- Will it be in person and hybrid again or in person only?

**Comment by dagendresen** [comment] 2023-04-26 14:59
Hi Luke,
* I think that Rukaya has filled in the venue booking form - and will let us know as soon as she gets a confirmation for the venue reservation (we COULD choose another venue if the Tøyen Manor is not free....).
* Yes, https://www.visitoslo.com/en/product/?tlp=2982773 is the venue we plan for.
* The max capacity is 70 people, but we were thinking of a setup with tables so people can more easily work from their laptops. Thus an estimated venue capacity of approx 35 people (but with a different setup we can make room for more - up to the max of 70 people).
* We plan for in-person - it is possible to set up a Zoom session for remote attendance. However, we were planning for in-person. And might rather suggest a separate virtual workshop....??? Hybrid workshops are very challenging to get to work well. (If somebody wants to log in and listen would be fine, but it is HARD to include them properly into the actual workshop).

**Comment by lhmarsden** [comment] 2023-04-27 07:20
>     * We plan for in-person - it is possible to set up a Zoom session for remote attendance. However, we were planning for in-person. And might rather suggest a separate virtual workshop....??? Hybrid workshops are very challenging to get to work well. (If somebody wants to log in and listen would be fine, but it is HARD to include them properly into the actual workshop).

Agree with this. I am in principle okay with a separate digital workshop.

**Comment by lhmarsden** [comment] 2023-04-27 07:23
> * approx 35 people

This is a good number. 70 is a lot! 

I will wait on confirmation on the venue before I make final changes.

**Comment by rukayaj** [comment] 2023-04-27 08:05
> Use of the Hall and the living rooms at Tøyen hovedgård on 21 and 22 September 2023 at 08:00 – 17:00 has been processed and approved.

So I think it's confirmed now.

**Comment by lhmarsden** [comment] 2023-04-27 08:18
Here is the link for signing up to the event:
https://www.eventbrite.com/e/bring-and-publish-your-data-workshop-darwin-core-archive-tickets-625228012817

What do you think? Anything that needs changing? Sign yourselves up!

I have put the max capacity at 40, but we can change this (or anything else) as needed.

Did you know that this is scheduled for 1 day after the anniversary of our last workshop together?!

**Comment by aaltenburger2** [comment] 2023-04-27 08:25
Looks good! I have signed up :-)

**Comment by lhmarsden** [comment] 2023-05-02 12:06
I see that a few of you have signed up. Would anyone like to propose any changes? Hit the thumbs up if you are okay with me to circulate this out to Nansen Legacy members now.

**Comment by ymgan** [comment] 2023-05-08 12:02
Heya! Thanks for inviting and sorry for informing late, I had to arrange my schedule with Anton since we have an Antarctic conference in New Zealand in early August, TDWG conference and GBIF meetings in Australia in October, plus my vacation back to Malaysia. All at that side of the globe ha ha ... 

Happy to let you know that I will be able to participate again this year. Please let me know how I can help and what cost should I cover from my end :) Cheers!

Btw, Anton is super impressed by what I learned last year and he likes @lhmarsden booking.com video 😄 so he said that he is interested to join this year if his schedule allows

**Comment by kkongshavn** [comment] 2023-05-10 13:06
I just now realized that this collides with Forskningstorget in Bergen - I'm likely to be on stand on the 22nd. We have a planning meeting later in May, I'll update once I know if I'm available.

**Comment by lhmarsden** [comment] 2023-06-22 09:40
Hi, someone has asked if accommodation is provided at Tøyen Manor. I assume not, but thought I shouldn't assume!?

**Comment by MichalTorma** [comment] 2023-06-22 10:10
> Hi, someone has asked if accommodation is provided at Tøyen Manor. I assume not, but thought I shouldn't assume!?

There is no accommodation at Tøyen (the whole botanical garden is closed at night) so your assumption was correct :)
@dagendresen might know which hotel is usually preferred for participants.

**Comment by dagendresen** [comment] 2023-06-22 17:28
I have noticed that the museum often book guest into [Thon hotel Spectrum](https://www.thonhotels.no/hoteller/norge/oslo/thon-hotel-spectrum/?utm_source=google&utm_medium=infoboks&utm_campaign=GMB). 
[Anker hotel](https://anker-hotel.no/) and [Anker hostel ](https://ankerhostel.no/)is even closer and lower priced. 
There is also a [hostel in Finnmarksgata](https://www.centralcityapartments.no/) and even closer. 
But any hotel or other accommodation in the city centre is good and with easy public transport to the museum!

I wrote some recommendations into the [2019 nodes meeting event page](https://www.gbif.no/events/2019/gbif-eu-2019.html) -- maybe somebody wants to write something similar into the [September 2023 event page](https://www.gbif.no/events/2023/nansen-legacy-oslo.html)??

**Comment by lhmarsden** [comment] 2023-06-23 08:26
Thanks Dag, I added this information on EventBrite

**Comment by lhmarsden** [comment] 2023-08-16 11:00
Hi folks, not long now until the workshop. I am now working at MET in Oslo.

We so far have 21 registered including instructors. There is interest from some other large marine research projects, so I am inviting a few people from them to fill up the rest of the places.

In the provisional schedule I included just 1 hour for introductory presentations. Is this okay with you? I think it would be useful to include an overview of the cores and extensions people are likely to use. I suspect everyone should be using event core and occurrence extension. Many will want to use eMoF. Some people have samples and might want to use the material sample extension. And some people will have measurements that relate to multiple occurrences so might want to use resource relationship extension. We can perhaps mention in passing some other extensions that are supported by GBIF Norway's IPT. 

I guess I will only need maybe 5-10 minutes to go through Nansen Legacy things e.g. wikidata and harvesting information from our metadata catalogue.

**Comment by rukayaj** [comment] 2023-08-23 09:59
I think 1 hour is ok :) Dag is adding some sub bullet points to the agenda

**Comment by lhmarsden** [comment] 2023-08-31 09:07
Should I ask for dietary requirements or is it a 'help yourself' kind of lunch?

**Comment by MichalTorma** [comment] 2023-08-31 09:23
> Should I ask for dietary requirements or is it a 'help yourself' kind of lunch?

I think it's good to ask - usually, we order catering so it would be useful (and if we decide to do something else it won't hurt)

**Comment by rukayaj** [comment] 2023-09-06 09:34
@lhmarsden we need to order catering. Do we have a list of participants + dietary requirements?

https://www.uio.no/for-ansatte/arbeidsstotte/arrangementsstotte/mat-servering/

**Comment by lhmarsden** [comment] 2023-09-06 10:52
I have a list of attendees but not dietary requirements yet. Do you have a deadline that I can communicate to people?

**Comment by rukayaj** [comment] 2023-09-06 13:57
It doesn't really say anything in the guidelines but it would be nice to know so I can get on with ordering it. They do say drop meat as an alternative, so we could do 10 vegan, 10 vegetarian, and maybe some should also be gluten free? Halal and Kosher people would then be fine too, so maybe that would cover all the options?

**Comment by rukayaj** [comment] 2023-09-06 13:59
Maybe ask them to get back to you by the end of the week if they have any special dietary requirements? Then i'll try order the food on Mon.

**Comment by lhmarsden** [comment] 2023-09-07 07:45
Survey circulated @rukayaj

**Comment by lhmarsden** [comment] 2023-09-11 07:00
I have emailed @rukayaj with the responses

**Comment by rukayaj** [comment] 2023-09-11 08:51
Super thanks @lhmarsden . @MichalTorma and I have filled out the catering request form, we should hear back soon.

**Comment by lhmarsden** [comment] 2023-09-14 11:19
Hi folks, just one week to go! Is there anything we need to discuss before then?

I think the plan is to start with a 1hr presentation from one/multiple of team GBIF. I will take 10 mins to provide some Nansen Legacy specific things and perhaps also present the template generator, which could be useful for those who are not in Nansen Legacy.

All okay?

I have time for a chat if necessary.

**Comment by rukayaj** [comment] 2023-09-14 11:33
Apparently catering is almost sorted out now - just waiting approval from upper management. 

I seem to remember @dagendresen made some notes about what we would cover in the 1 hour presentation, and who would cover what, but I don't see those notes anywhere now. Does anyone have a link to this somewhere?

**Comment by dagendresen** [comment] 2023-09-14 12:09
At what hour do we start? at 09:00? (maybe update times at https://www.gbif.no/events/2023/nansen-legacy-oslo.html)

Note that I will be stuck in the GBIF Norway Node Board meeting from 09 to 11 on Thursday 21 September (on the first day of the workshop). I will join as soon as I can!

I believe/hope that we already discussed who will make the GBIF introduction presentation.
I think that we also discussed a much shorter intro than 60 minutes?

**Comment by lhmarsden** [comment] 2023-09-14 12:25
We start at 9. Details here: https://www.eventbrite.com/e/bring-and-publish-your-data-workshop-darwin-core-archive-tickets-625228012817

Less than 1 hour is also okay!

See you whenever you arrive, Dag :)

**Comment by rukayaj** [comment] 2023-09-14 12:28
Yes, the https://www.gbif.no/events/2023/nansen-legacy-oslo.html page is what I was remembering. 

But if @dagendresen isn't available in the morning one of the rest of us needs to do his Intro to GBIF 15 minute presentation? I guess probably me, unless someone else wants to do it?

**Comment by dagendresen** [comment] 2023-09-14 12:39
Maybe a hard selection from the [NMBU workshop slides (96 slides!)](https://docs.google.com/presentation/d/1isziNYg51m-4G5ihwMUKXmBBXiArvXo3/edit?usp=drive_web&ouid=115547050550954466285&rtpof=true) might be a possible starting point?
https://www.gbif.no/events/2023/data-and-stats-forum-at-mina-nmbu.html
https://drive.google.com/drive/folders/1Gf1Qw1B8dTxRiVG2eb42iJc9E8JNrlkp

**Comment by rukayaj** [comment] 2023-09-14 19:03
96 slides dag!??!! 😱 🤣

**Comment by lhmarsden** [comment] 2023-09-18 07:44
I have created a google drive for the workshop. Feel free to add and edit what you like. Everything included so far is from our previous workshop last year.

You should all have editor privileges. Anyone else has read-only.

https://drive.google.com/drive/folders/1H5T2vLW2Wl6SkdACMPO7Spk7_wvRHlVP?usp=drive_link

**Comment by rukayaj** [comment] 2023-09-28 09:45
I don't think we actually had any datasets published in this workshop, but hopefully some should come out of it! Closing this issue.

**Closed as completed by rukayaj** 2023-09-28 09:45 UTC
Labels: data mobilisation, marine data, workshop

**Comment by aaltenburger2** [comment] 2023-09-28 10:29
There are several datasets in the pipeline. This one got published today Macrobenthos of the continental slope north of Svalbard from the Nansen Legacy joint cruise JC3 in Feb/Mar 2023. (gbif.org)<https://www.gbif.org/dataset/1a8e24f2-98dd-4028-9a6a-66539db4e2ef>

**Comment by rukayaj** [comment] 2023-10-02 11:20
Based on feedback for this workshop - we should remember for next time to do a formal, slower and more thorough step by step guide for the IPT, and maybe not bother with an introduction to GBIF or what darwin core is etc.

**Comment by lhmarsden** [comment] 2023-10-02 11:51
I personally think a brief introduction to GBIF and Darwin Core is important, but perhaps 5-10 minutes on each is enough.

**Comment by lhmarsden** [comment] 2023-10-02 11:53
And I agree in part about the IPT, but in my opinion the most important think to spend time on is how to structure the data. Which core to choose? Which extensions? Which columns should be included? Perhaps some focus on experimental data from scientists. Also, many people had cross-tab data, so this could be useful.

I think once you have the 'source' data for the IPT, using the IPT itself is quite easy.

**Comment by aaltenburger2** [comment] 2023-10-02 12:16
[like]  Andreas Altenburger reacted to your message:
________________________________
